[[RNAstructure]]
arch = "aarch64"
git-tree-sha1 = "005ddb6ab258e0b2a63d300a92080c772510ff3c"
os = "macos"

    [[RNAstructure.download]]
    sha256 = "de08e007a247a0b52d397ce0965ef11b24b9e343c726816bb20c7539fefc0e36"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.aarch64-apple-darwin.tar.gz"
[[RNAstructure]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "179f2a79201b92666e9880b0c1f2dc55ea4e4353"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "9b83bbebae7ea4892cb4627f434df86c060876f5a8bda5b65899081fe28c5602"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[RNAstructure]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac5aacf7c3223093b8659288fea9764d12d5032e"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "e5a0a41239f5707fea9d6035988163154e6769f7c92e6e9a82a8f360f329c17a"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[RNAstructure]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb7e8c7801c48aa1b900506f3b58ed7c9fedfb1e"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "b620b8dc9211a999dd3ade5db6c134bf17210cd3d56063e155689b63cce69ab9"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[RNAstructure]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25bbf3758d254679c74e3a0b255748c11b386d9f"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "f9947cac51eb453081fce9ab2a6ccf1c9d5d070bc79954c972a454bbe053d2ca"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[RNAstructure]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7703255bd3353ac2a580a0ae36263e3d263295a9"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "47b5f8d37bb4592b49d1dc8b5b99a5c0e1da2063672c35f3f1574ab69e7359f2"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[RNAstructure]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "126d0010206186bcb0b8b9ba5b09363e48de4fa6"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "1d9dcf273f7791951c0796c918da60bdbaa19a9060e52c7293647e76080b327f"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[RNAstructure]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8297d33927446c8386cf8ea787ff827ecc6abb30"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "cc758d04f582e347a074b632cd9009d8059f7a499200c60007956414938befe9"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[RNAstructure]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ee578a3aa75653e2625610d143d897748363ace"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "fe081153c8427330e3d025412bcfb8f97b252808e88c85577107f9d7f838867a"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[RNAstructure]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab7f87a128fed2253a0bba2c82f392cc37457cb2"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "aed3ec4df80c141031f4c562dbc787c7486d4cbe574d493298c7541fb51fe90d"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[RNAstructure]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56545f8c4a20748e89c0b74ea3ed4915400cf9ce"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "3e62ae4517b544392959960c065ed6e1b301ba35f09f4e75ab27ab7bce7485c3"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[RNAstructure]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4058f216809dd80798b10b4a58dd52e5bf47193"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "c9184f6d9da4e9e3e794b4ab54f6be31abf03e7c5a72670fcc290e5c94f07d02"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[RNAstructure]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eb7b48a868ac3404e0f5437887b085d71578424"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "a77a09b529c56157261ec97314943cec27bf194564769b56177e41de3325ee2b"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68cf333f73367902ac234e15feed3206881ae672"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "64fefa9b0f7677681763146cb854831eb3247946d08780f06e9d806a724d6dca"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-linux-gnu-cxx03.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36eaff48f62c68afe44f112e3ca237fe6c468837"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "27a5f176c65cb8c43f93a5a5e92d95eaebe0acde32a2cc64d97fb853de712214"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-linux-gnu-cxx11.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "927aae120edc084c8b53cfa790487c57f00f3d5b"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "dacb33f2d5b80fca1400ccfd1a538cda4fb254cf26234fc431636bd0129b1fef"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-linux-musl-cxx03.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52955f89ef4a8742a26ea211f21edfec4954ae2d"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "a5a27ee005681419456f5dbbf8ad7bcab522c3dd05116cbee6e7dc20a2625f60"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-linux-musl-cxx11.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b7bb30e68430ebbcc61685d168c638d355524bc"
os = "windows"

    [[RNAstructure.download]]
    sha256 = "b767b92252aa4885292e34c89b00912169cd3636ef11259615d69300380ca65b"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[RNAstructure]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba5266e643e575c81b4928a56a11fd0a26e1f345"
os = "windows"

    [[RNAstructure.download]]
    sha256 = "b78320b2d90f7db73c3fb5779c09c16f406100426c9d6b071af541b1ecab93e7"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[RNAstructure]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f349665372203ab7064db0a56e16a8500c3e2b85"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "cb3f9d3a9cfe5dd6728cd7de2b5f469d566646c54433270ee9a205bfcb6e076d"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[RNAstructure]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ac8594d578fab1663c517dd69facf3835624a3f"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "155133e1a6d8fe93ede5cf6755dba6aa4d05713cec2bb84af317368182f0de97"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[RNAstructure]]
arch = "x86_64"
git-tree-sha1 = "a720040b2132196844aa775e92658500f0101056"
os = "macos"

    [[RNAstructure.download]]
    sha256 = "3c72f29bdb3ca8d9f7b88f5b06d9c05953d96f909d880c773ac5a2fd826fa78a"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-apple-darwin.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "158b48e8b155ecbc2b787df852530158ac729430"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "c4215a3dbe716e7c59290fba189a0e1c6169f710585feac94f18f447ed43f015"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4349d59ce818b396fc72126dddfe99cce0e346d5"
libc = "glibc"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "e3e47a82b0720e56d10e3217d7ab2266156e630c1c1c9428225447a7d08bb54e"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a027f2337c3d4a3f761c20e1ad1ca5f44c92f14"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "84cd61a54245a38e0608ba00e2cf6e8af99964b5a9f64b9a017db77080b07b9e"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b8ab1124f3295a3a73083f211ffc3e3efc0960a"
libc = "musl"
os = "linux"

    [[RNAstructure.download]]
    sha256 = "c4c48cf91d8a7aaaf7e3bf94fe5ce1df3aaa4152c11e7edc53b74edd1bf3fe94"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[RNAstructure]]
arch = "x86_64"
git-tree-sha1 = "cf0bf4135018bcb06f00bcda334ed527b4cf11da"
os = "freebsd"

    [[RNAstructure.download]]
    sha256 = "048ed0166621ec7ca1a02dc22e032e4eb5fd2357a0c7b2a5df5c74a38426c117"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-unknown-freebsd.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "128743a05b9201cbd0ca3d7b7d6733756bc05f3e"
os = "windows"

    [[RNAstructure.download]]
    sha256 = "32d3634d0401e2d5c84e33a008b500bfd4cd7efcb4cea504f8b54bad36276d4e"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[RNAstructure]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32874d193d6b989fde258517752e56807a4e9967"
os = "windows"

    [[RNAstructure.download]]
    sha256 = "11ea4804afbcbe503114302436d392b11e5e4560c5161b8e82775c21218e8e9c"
    url = "https://github.com/JuliaBinaryWrappers/RNAstructure_jll.jl/releases/download/RNAstructure-v6.4.0+1/RNAstructure.v6.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
